import test from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {createDesktopRuntime} from '../runtime.mjs';
globalThis.crypto ||= webcrypto;
function bridge(cacheMiss=false){let listener;const calls=[];return {calls,event:{listen:async(_,fn)=>{listener=fn;return ()=>{listener=null;};}},core:{invoke:async(name,args)=>{calls.push({name,args});if(name==='native_start'){queueMicrotask(()=>listener?.({payload:{jobId:args.request.jobId,type:args.request.type==='qualify'?'qualified':'completed',deviceValidated:true,cacheMiss:cacheMiss&&args.request.cacheOnly===true,localArtifactId:'result',cached:true}}));}if(name==='native_read_artifact')return (args.file==='result.json'?new TextEncoder().encode(JSON.stringify({values:Array(9216).fill(.2),space:'w-plus',shape:[1,18,512]})):new Uint8Array([137,80,78,71])).buffer;}}};}
test('native qualification then media and editable latent retrieval use bounded host commands',async()=>{const tauri=bridge(),runtime=createDesktopRuntime({tauri});assert.equal((await runtime.qualify()).deviceValidated,true);const result=await runtime.generate({mode:'seed',value:'0'});assert.equal(result.blob.type,'image/png');assert.equal(result.values.length,9216);assert.equal(result.cached,true);assert.equal(tauri.calls.filter(x=>x.name==='native_read_artifact').length,2);assert.equal(tauri.calls[1].args.request.operation,'generate');});
test('IPC registration failure is reported and does not wedge next operation',async()=>{const tauri=bridge();tauri.event.listen=async()=>{throw Error('event registration failed');};const runtime=createDesktopRuntime({tauri});await assert.rejects(runtime.qualify(),/registration failed/);assert.equal(runtime.status().busy,false);});
test('does not imply GPU or malformed latent qualification',async()=>{const runtime=createDesktopRuntime({tauri:bridge()});await assert.rejects(runtime.qualify('gpu'),/GPU/);await runtime.qualify();assert.throws(()=>runtime.synthesize({space:'w-plus',shape:[1,18,512],values:[1]}),/Invalid/);});

test('cancel while event registration is pending never starts a worker',async()=>{const tauri=bridge();let registered;tauri.event.listen=()=>new Promise(resolve=>{registered=resolve;});const runtime=createDesktopRuntime({tauri});const work=runtime.qualify();runtime.cancel();registered(()=>{});await assert.rejects(work,{name:'AbortError'});await new Promise(resolve=>setTimeout(resolve,0));assert.equal(tauri.calls.some(x=>x.name==='native_start'),false);});

test('cached native original can load before any model qualification',async()=>{const tauri=bridge(),runtime=createDesktopRuntime({tauri});const value=await runtime.generate({mode:'seed',value:'0'});assert.equal(value.cached,true);assert.equal(tauri.calls.find(x=>x.name==='native_start').args.request.cacheOnly,true);assert.equal(tauri.calls.some(x=>x.name==='native_start'&&x.args.request.type==='qualify'),false);});

test('native cache miss qualifies before uncached generation',async()=>{const tauri=bridge(true),runtime=createDesktopRuntime({tauri});await runtime.generate({mode:'seed',value:'0'});const commands=tauri.calls.filter(x=>x.name==='native_start').map(x=>x.args.request);assert.equal(commands.length,3);assert.equal(commands[0].cacheOnly,true);assert.equal(commands[1].type,'qualify');assert.equal(commands[2].cacheOnly,undefined);assert.equal(runtime.status().deviceValidated,true);});
