import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {inputLatent,truncate,rgba1024} from './identity.mjs';
import {digest} from './originals.mjs';
const fixture=JSON.parse(await readFile(new URL('./identity-fixtures.json',import.meta.url)));
for(const c of fixture.cases)test(`Exact NumPy identity: ${c.mode} ${c.value}`,async()=>assert.equal(await digest((await inputLatent(c.mode,c.value)).values),c.sha256));
test('Reject unsafe seeds and oversized text',async()=>{for(const value of ['-1','1.5','4294967296','1e3',''])await assert.rejects(inputLatent('seed',value));await assert.rejects(inputLatent('text','😀'.repeat(129)));});
test('Truncation applies exactly first eight layers, no alias',()=>{const w=new Float32Array(9216).fill(1),a=new Float32Array(512).fill(.25),t=truncate(w,a);assert.equal(t[0],Math.fround(.25+Math.fround(Math.fround(1-.25)*Math.fround(.7))));assert.equal(t[4096],1);assert.equal(w[0],1);});
test('Pixel conversion refuses NaN instead of black successful image',()=>{const raw=new Float32Array(3*1024*1024);raw[0]=NaN;assert.throws(()=>rgba1024(raw),/Nonfinite/);});
import {generationIdentity} from './identity.mjs';
import {decodeReferencePng,encodeRgbaPng} from './png.mjs';
test('Moving hosts or changing canaries preserves original identity, weights invalidate',()=>{const m={synthesis:{sha256:'a',url:'https://one'},mapping:{sha256:'b'},average:{sha256:'c'},noise:[{name:'noise_0',shape:[4,4],sha256:'d'}]},moved={...m,synthesis:{...m.synthesis,url:'https://two'},canaries:['more'],releaseQualified:true};assert.deepEqual(generationIdentity(m,'seed'),generationIdentity(moved,'seed'));assert.notDeepEqual(generationIdentity(m,'seed'),generationIdentity({...m,synthesis:{sha256:'changed'}},'seed'));});
test('Canonical PNG exact raw byte roundtrip without canvas',async()=>{const raw=Uint8Array.from({length:16*16*4},(_,i)=>i%256);const png=await encodeRgbaPng(raw,16,16);const decoded=await decodeReferencePng(await png.arrayBuffer(),{expectedWidth:16,expectedHeight:16});assert.deepEqual(new Uint8Array(decoded.rgba),raw);});
import {createBrowserRuntime} from './runtime.mjs';
const testManifest=()=>({schemaVersion:1,bundleVersion:'test-controller-only',modelSourceSha256:'source',noiseSha256:'noise',canaries:[{},{}],synthesis:{sha256:'s'},mapping:{sha256:'m'},average:{sha256:'a'},noise:[],webgpu:{}});
function fakeStorage(){const values=new Map();return {getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};}
test('GPU failure terminates before an independently checked CPU retry',async()=>{const oldNav=Object.getOwnPropertyDescriptor(globalThis,'navigator');Object.defineProperty(globalThis,'navigator',{configurable:true,value:{gpu:{}}});globalThis.sessionStorage=fakeStorage();const calls=[];const runtime=createBrowserRuntime({manifestSha256:'0'.repeat(64),manifest:testManifest(),workerFactory:()=>{let provider;return {postMessage(message){if(message.type==='initialize')provider=message.provider;calls.push(message.type+':'+provider);queueMicrotask(()=>this.onmessage({data:message.type==='qualify'&&provider==='webgpu'?{id:message.id,type:'error',error:{name:'Error',message:'Driver failed'}}:{id:message.id,type:'complete',result:message.type==='generate'?{blob:new Blob(['controller-test-only'],{type:'image/png'}),values:new Float32Array(9216),space:'w-plus',shape:[1,18,512]}:{deviceValidated:true}}}));},terminate(){calls.push('terminate:'+provider);}};}});try{const result=await runtime.generate({mode:'seed',value:'3'});assert.equal(result.provenance.provider,'wasm');assert.deepEqual(calls.slice(0,7),['initialize:webgpu','qualify:webgpu','terminate:webgpu','initialize:wasm','qualify:wasm','generate:wasm']);}finally{runtime.dispose();if(oldNav)Object.defineProperty(globalThis,'navigator',oldNav);else delete globalThis.navigator;delete globalThis.sessionStorage;}});
test('Phone monolithic encoder guard fires before worker or alignment allocation',async()=>{const oldNav=Object.getOwnPropertyDescriptor(globalThis,'navigator');Object.defineProperty(globalThis,'navigator',{configurable:true,value:{userAgent:'iPhone',maxTouchPoints:5}});let allocations=0;const runtime=createBrowserRuntime({manifestSha256:'0'.repeat(64),manifest:{...testManifest(),encoder:{size:1068862265,sha256:'encoder'}},alignPhoto:async()=>{allocations++;throw Error('Must not align');},workerFactory:()=>{allocations++;throw Error('Must not allocate');}});try{await assert.rejects(runtime.encodePhoto(new Blob(['synthetic-input'])),/too large/);assert.equal(allocations,0);}finally{runtime.dispose();if(oldNav)Object.defineProperty(globalThis,'navigator',oldNav);else delete globalThis.navigator;}});
